version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  
  back:
    build:
      context: ./backend/
      dockerfile: Dockerfile_dev
    volumes:
      - ./backend:/journey/backend
    ports:
      - "3010:3010"
    depends_on:
      - db
    tty: true
    stdin_open: true
 
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: 'yarn start'
    volumes:
      - ./frontend/:/journey/frontend
    ports:
      - "3000:3000"