# 将来的に対応予定の規約の読み込み
inherit_from: .rubocop_todo.yml

# 追加した規約ファイルを読み込む
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Max: 30

# Gemfileは DSL 的で基本的に複雑にはならないので除外
# rake, rspec, environments, routes は巨大な block 不可避なので除外
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"

# 20 行超えるのは migration ファイル以外滅多に無い
Metrics/MethodLength:
  Max: 30

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# spec_helper内は許可
Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# frozen_string_literal: true を不要にする
Style/FrozenStringLiteralComment:
  Enabled: false

# %wは()で囲うようにする
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'

# 日本語だと「〜の場合」になるため、when, with, withoutでスタートする必要性を無視
RSpec/ContextWording:
  Enabled: false

# 1つのExampleの最大行数を8にする
RSpec/ExampleLength:
  Max: 8

# 1つのExample内で使用できるletの最大数を6にする
RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 4