source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4'
# databaseとしてMySQLを使う
gem 'mysql2', '~> 0.5'
# Appサーバーとしてpumaを使う
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# 認証機能用のgemであるdeviseを使う
gem 'devise'
gem 'devise-i18n'
gem 'devise_token_auth'
# ソーシャルログインのためのgem
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-rails_csrf_protection'
# ファイルアップロード機能として、carrierwaveを使う
gem 'carrierwave'
gem 'mini_magick'

# シリアライズのためのgem
gem 'active_model_serializers'
# 住所から緯度と経度を取得するためのgem
gem 'geocoder'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # rspecを導入するためのgem
  gem 'rspec-rails', '~> 5.0.0'
  # テストデータを作成するgem
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # コード解析ツールとしてrubocopを使う
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  # commit前にrubocopを実行させるために導入する
  gem 'pre-commit', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
